name: Ecommerce CI
on:
  push: 
    branches: [ main ]
    pull_request: [ master ]
  
jobs: 
  builds:
    env:
     CI: true
     MONGO_URL: mongodb+srv://e-commerce:olamide16@cluster0.kshfbjx.mongodb.net/?retryWrites=true&w=majority
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: [ '4.4' ]
      runs-on: ubuntu-latest
      steps:
        -uses: action/checkout@v3
        -name: Use Node.js version ${{ matrix.node-version}}
          with:
            node-version: ${{ matrix.node-version}}
        -run: npm install
        -run: npm run start
        -run: npm run test
